/**
 * 英単語データ
 * 学年レベルごとに「英語 / 日本語」のペアを持つ。
 * en: 英単語（発音に使う） / ja: 日本語の意味
 */
const VOCAB = {
  es: {
    label: '小学生',
    icon: '🌱',
    desc: '身のまわりの基本単語',
    color: '#4ade80',
    words: [
      { en: 'dog', ja: 'いぬ' },
      { en: 'cat', ja: 'ねこ' },
      { en: 'bird', ja: 'とり' },
      { en: 'fish', ja: 'さかな' },
      { en: 'rabbit', ja: 'うさぎ' },
      { en: 'monkey', ja: 'さる' },
      { en: 'elephant', ja: 'ぞう' },
      { en: 'lion', ja: 'ライオン' },
      { en: 'bear', ja: 'くま' },
      { en: 'horse', ja: 'うま' },
      { en: 'apple', ja: 'りんご' },
      { en: 'banana', ja: 'バナナ' },
      { en: 'bread', ja: 'パン' },
      { en: 'milk', ja: 'ぎゅうにゅう' },
      { en: 'egg', ja: 'たまご' },
      { en: 'rice', ja: 'ごはん' },
      { en: 'water', ja: 'みず' },
      { en: 'cake', ja: 'ケーキ' },
      { en: 'meat', ja: 'にく' },
      { en: 'juice', ja: 'ジュース' },
      { en: 'red', ja: 'あか' },
      { en: 'blue', ja: 'あお' },
      { en: 'yellow', ja: 'きいろ' },
      { en: 'green', ja: 'みどり' },
      { en: 'black', ja: 'くろ' },
      { en: 'white', ja: 'しろ' },
      { en: 'pink', ja: 'ピンク' },
      { en: 'brown', ja: 'ちゃいろ' },
      { en: 'pencil', ja: 'えんぴつ' },
      { en: 'book', ja: 'ほん' },
      { en: 'desk', ja: 'つくえ' },
      { en: 'chair', ja: 'いす' },
      { en: 'teacher', ja: 'せんせい' },
      { en: 'student', ja: 'せいと' },
      { en: 'school', ja: 'がっこう' },
      { en: 'notebook', ja: 'ノート' },
      { en: 'eraser', ja: 'けしゴム' },
      { en: 'bag', ja: 'かばん' },
      { en: 'father', ja: 'おとうさん' },
      { en: 'mother', ja: 'おかあさん' },
      { en: 'brother', ja: 'きょうだい（兄・弟）' },
      { en: 'sister', ja: 'しまい（姉・妹）' },
      { en: 'friend', ja: 'ともだち' },
      { en: 'grandfather', ja: 'おじいさん' },
      { en: 'grandmother', ja: 'おばあさん' },
      { en: 'head', ja: 'あたま' },
      { en: 'hand', ja: 'て' },
      { en: 'foot', ja: 'あし' },
      { en: 'eye', ja: 'め' },
      { en: 'ear', ja: 'みみ' },
      { en: 'mouth', ja: 'くち' },
      { en: 'nose', ja: 'はな（鼻）' },
      { en: 'sun', ja: 'たいよう' },
      { en: 'moon', ja: 'つき' },
      { en: 'star', ja: 'ほし' },
      { en: 'rain', ja: 'あめ' },
      { en: 'snow', ja: 'ゆき' },
      { en: 'tree', ja: 'き（木）' },
      { en: 'flower', ja: 'はな（花）' },
      { en: 'sky', ja: 'そら' },
      { en: 'river', ja: 'かわ' },
      { en: 'mountain', ja: 'やま' },
      { en: 'run', ja: 'はしる' },
      { en: 'eat', ja: 'たべる' },
      { en: 'sleep', ja: 'ねる' },
      { en: 'play', ja: 'あそぶ' },
      { en: 'sing', ja: 'うたう' },
      { en: 'swim', ja: 'およぐ' },
      { en: 'read', ja: 'よむ' },
      { en: 'write', ja: 'かく' },
      { en: 'walk', ja: 'あるく' },
      { en: 'jump', ja: 'とぶ' }
    ]
  },

  jhs: {
    label: '中学生',
    icon: '⚡',
    desc: '教科書レベルの必修単語',
    color: '#38bdf8',
    words: [
      { en: 'arrive', ja: '到着する' },
      { en: 'borrow', ja: '借りる' },
      { en: 'choose', ja: '選ぶ' },
      { en: 'decide', ja: '決める' },
      { en: 'explain', ja: '説明する' },
      { en: 'forget', ja: '忘れる' },
      { en: 'invite', ja: '招待する' },
      { en: 'introduce', ja: '紹介する' },
      { en: 'practice', ja: '練習する' },
      { en: 'remember', ja: '覚えている' },
      { en: 'return', ja: '戻る・返す' },
      { en: 'understand', ja: '理解する' },
      { en: 'agree', ja: '賛成する' },
      { en: 'believe', ja: '信じる' },
      { en: 'carry', ja: '運ぶ' },
      { en: 'collect', ja: '集める' },
      { en: 'hurry', ja: '急ぐ' },
      { en: 'improve', ja: '上達する' },
      { en: 'receive', ja: '受け取る' },
      { en: 'worry', ja: '心配する' },
      { en: 'important', ja: '重要な' },
      { en: 'difficult', ja: '難しい' },
      { en: 'easy', ja: '簡単な' },
      { en: 'famous', ja: '有名な' },
      { en: 'dangerous', ja: '危険な' },
      { en: 'quiet', ja: '静かな' },
      { en: 'careful', ja: '注意深い' },
      { en: 'expensive', ja: '高価な' },
      { en: 'popular', ja: '人気のある' },
      { en: 'similar', ja: '似ている' },
      { en: 'useful', ja: '役に立つ' },
      { en: 'strange', ja: '奇妙な' },
      { en: 'delicious', ja: 'とてもおいしい' },
      { en: 'necessary', ja: '必要な' },
      { en: 'culture', ja: '文化' },
      { en: 'environment', ja: '環境' },
      { en: 'experience', ja: '経験' },
      { en: 'future', ja: '未来' },
      { en: 'health', ja: '健康' },
      { en: 'hobby', ja: '趣味' },
      { en: 'information', ja: '情報' },
      { en: 'language', ja: '言語' },
      { en: 'memory', ja: '記憶・思い出' },
      { en: 'nature', ja: '自然' },
      { en: 'opinion', ja: '意見' },
      { en: 'problem', ja: '問題' },
      { en: 'reason', ja: '理由' },
      { en: 'result', ja: '結果' },
      { en: 'subject', ja: '教科' },
      { en: 'tradition', ja: '伝統' },
      { en: 'volunteer', ja: 'ボランティア' },
      { en: 'weather', ja: '天気' },
      { en: 'message', ja: 'メッセージ' },
      { en: 'chance', ja: '機会' },
      { en: 'holiday', ja: '休日' },
      { en: 'machine', ja: '機械' },
      { en: 'neighbor', ja: '近所の人' },
      { en: 'safety', ja: '安全' },
      { en: 'however', ja: 'しかしながら' },
      { en: 'especially', ja: '特に' },
      { en: 'suddenly', ja: '突然' },
      { en: 'finally', ja: 'ついに' },
      { en: 'usually', ja: 'たいてい' },
      { en: 'probably', ja: 'たぶん' },
      { en: 'instead', ja: '代わりに' },
      { en: 'almost', ja: 'ほとんど' }
    ]
  },

  hs: {
    label: '高校生',
    icon: '🔥',
    desc: '入試・共通テスト頻出',
    color: '#fb923c',
    words: [
      { en: 'achieve', ja: '達成する' },
      { en: 'analyze', ja: '分析する' },
      { en: 'appreciate', ja: '感謝する・良さがわかる' },
      { en: 'assume', ja: '想定する' },
      { en: 'avoid', ja: '避ける' },
      { en: 'concentrate', ja: '集中する' },
      { en: 'consider', ja: '熟考する' },
      { en: 'contribute', ja: '貢献する' },
      { en: 'demand', ja: '要求する' },
      { en: 'describe', ja: '描写する' },
      { en: 'encourage', ja: '励ます' },
      { en: 'establish', ja: '設立する' },
      { en: 'maintain', ja: '維持する' },
      { en: 'obtain', ja: '入手する' },
      { en: 'prevent', ja: '防ぐ' },
      { en: 'provide', ja: '提供する' },
      { en: 'recognize', ja: '認識する' },
      { en: 'reduce', ja: '減らす' },
      { en: 'replace', ja: '取り替える' },
      { en: 'suggest', ja: '提案する' },
      { en: 'survive', ja: '生き残る' },
      { en: 'indicate', ja: '示す' },
      { en: 'advantage', ja: '利点' },
      { en: 'argument', ja: '議論・主張' },
      { en: 'attitude', ja: '態度' },
      { en: 'benefit', ja: '利益・恩恵' },
      { en: 'challenge', ja: '課題・挑戦' },
      { en: 'circumstance', ja: '状況' },
      { en: 'community', ja: '地域社会' },
      { en: 'conflict', ja: '対立' },
      { en: 'consequence', ja: '結果・影響' },
      { en: 'crisis', ja: '危機' },
      { en: 'evidence', ja: '証拠' },
      { en: 'influence', ja: '影響' },
      { en: 'method', ja: '方法' },
      { en: 'opportunity', ja: '機会' },
      { en: 'phenomenon', ja: '現象' },
      { en: 'policy', ja: '政策・方針' },
      { en: 'principle', ja: '原則' },
      { en: 'progress', ja: '進歩' },
      { en: 'purpose', ja: '目的' },
      { en: 'quality', ja: '質' },
      { en: 'responsibility', ja: '責任' },
      { en: 'society', ja: '社会' },
      { en: 'strategy', ja: '戦略' },
      { en: 'technology', ja: '科学技術' },
      { en: 'theory', ja: '理論' },
      { en: 'value', ja: '価値' },
      { en: 'ancient', ja: '古代の' },
      { en: 'appropriate', ja: '適切な' },
      { en: 'complex', ja: '複雑な' },
      { en: 'efficient', ja: '効率的な' },
      { en: 'essential', ja: '不可欠な' },
      { en: 'gradual', ja: '徐々の' },
      { en: 'obvious', ja: '明らかな' },
      { en: 'potential', ja: '潜在的な' },
      { en: 'previous', ja: '以前の' },
      { en: 'reliable', ja: '信頼できる' },
      { en: 'significant', ja: '重要な・著しい' },
      { en: 'sufficient', ja: '十分な' },
      { en: 'temporary', ja: '一時的な' },
      { en: 'various', ja: 'さまざまな' },
      { en: 'eventually', ja: '最終的に' },
      { en: 'regardless', ja: '〜に関係なく' },
      { en: 'therefore', ja: 'それゆえに' }
    ]
  },

  univ: {
    label: '大学生',
    icon: '👑',
    desc: 'アカデミック・資格試験',
    color: '#c084fc',
    words: [
      { en: 'abstract', ja: '抽象的な' },
      { en: 'accumulate', ja: '蓄積する' },
      { en: 'adequate', ja: '十分な・適切な' },
      { en: 'advocate', ja: '擁護する・提唱する' },
      { en: 'aesthetic', ja: '美的な' },
      { en: 'ambiguous', ja: '曖昧な' },
      { en: 'analogy', ja: '類推・たとえ' },
      { en: 'anticipate', ja: '予期する' },
      { en: 'arbitrary', ja: '恣意的な' },
      { en: 'assess', ja: '評価する' },
      { en: 'coherent', ja: '首尾一貫した' },
      { en: 'comprehensive', ja: '包括的な' },
      { en: 'constitute', ja: '構成する' },
      { en: 'correlation', ja: '相関関係' },
      { en: 'criterion', ja: '基準' },
      { en: 'cumulative', ja: '累積的な' },
      { en: 'deduce', ja: '演繹する・推論する' },
      { en: 'derive', ja: '引き出す・由来する' },
      { en: 'discrepancy', ja: '食い違い' },
      { en: 'empirical', ja: '経験的な・実証的な' },
      { en: 'explicit', ja: '明示的な' },
      { en: 'feasible', ja: '実行可能な' },
      { en: 'framework', ja: '枠組み' },
      { en: 'hypothesis', ja: '仮説' },
      { en: 'implement', ja: '実施する' },
      { en: 'implication', ja: '含意・影響' },
      { en: 'infer', ja: '推測する' },
      { en: 'inherent', ja: '本来備わった' },
      { en: 'integrate', ja: '統合する' },
      { en: 'intervene', ja: '介入する' },
      { en: 'legitimate', ja: '正当な' },
      { en: 'magnitude', ja: '規模・重要度' },
      { en: 'manipulate', ja: '巧みに操作する' },
      { en: 'methodology', ja: '方法論' },
      { en: 'nevertheless', ja: 'それにもかかわらず' },
      { en: 'norm', ja: '規範' },
      { en: 'paradigm', ja: 'パラダイム・理論的枠組み' },
      { en: 'perceive', ja: '知覚する' },
      { en: 'preliminary', ja: '予備的な' },
      { en: 'presume', ja: '推定する' },
      { en: 'prevalent', ja: '広く行き渡った' },
      { en: 'prominent', ja: '著名な・目立つ' },
      { en: 'refute', ja: '論破する' },
      { en: 'reluctant', ja: '気が進まない' },
      { en: 'subsequent', ja: 'その後の' },
      { en: 'substantial', ja: 'かなりの' },
      { en: 'synthesis', ja: '統合・合成' },
      { en: 'terminology', ja: '専門用語' },
      { en: 'threshold', ja: '閾値・境目' },
      { en: 'transition', ja: '移行' },
      { en: 'underlying', ja: '根底にある' },
      { en: 'utilize', ja: '活用する' },
      { en: 'validity', ja: '妥当性' },
      { en: 'viable', ja: '存続可能な' },
      { en: 'virtually', ja: '事実上' },
      { en: 'conversely', ja: '逆に言えば' },
      { en: 'scrutiny', ja: '綿密な調査' },
      { en: 'consensus', ja: '合意' },
      { en: 'incentive', ja: '動機づけ・誘因' },
      { en: 'plausible', ja: 'もっともらしい' },
      { en: 'redundant', ja: '冗長な' },
      { en: 'sustain', ja: '持続させる' },
      { en: 'compile', ja: '編集する・まとめる' },
      { en: 'exert', ja: '（力を）行使する' }
    ]
  }
};

/** 遊び方（札の取り方） */
const MODES = {
  taisen: {
    label: 'かるた対戦',
    icon: '🀄',
    desc: '読み手の声を聞いて相手と札を取り合う十二枚勝負',
    cards: 12
  },
  hitori: {
    label: 'ひとりかるた',
    icon: '⏳',
    desc: '60秒で何枚取れるか。札はどんどん補充される',
    cards: 12,
    time: 60
  }
};

/**
 * 読み方。
 * en … 英語を読み上げる → 場に並ぶ「日本語の取り札」を取る
 * ja … 日本語を読む     → 場に並ぶ「英語の取り札」を取る
 * mix … 札ごとに面が違い、読み方も札に合わせて変わる
 */
const READ_STYLES = {
  mix: { label: 'ミックス', icon: '🎴', desc: '英語読みと日本語読みが混ざる', needsSpeech: true },
  en:  { label: '英語読み', icon: '🎧', desc: '発音を聞いて日本語の札を取る', needsSpeech: true },
  ja:  { label: '日本語読み', icon: '📖', desc: '日本語を見て英語の札を取る' }
};

/** 対戦相手（取りにいくまでの速さ・ミリ秒） */
const OPPONENTS = {
  kids:   { label: 'こども名人', icon: '🧒', min: 3600, max: 5400 },
  town:   { label: '町内会の猛者', icon: '🧑', min: 2500, max: 3900 },
  club:   { label: 'かるた部主将', icon: '🎓', min: 1800, max: 2800 },
  meijin: { label: '永世名人', icon: '👹', min: 1150, max: 1900 }
};

const LEVEL_ORDER = ['es', 'jhs', 'hs', 'univ'];
const MODE_ORDER = ['taisen', 'hitori'];
const STYLE_ORDER = ['mix', 'en', 'ja'];
const OPPONENT_ORDER = ['kids', 'town', 'club', 'meijin'];
